-- =============================================
-- 중고거래 플랫폼 Oracle DB 초기화 스크립트
-- 실행 전 기존 객체 삭제 후 실행할 것
-- =============================================

-- =============================================
-- 1. 시퀀스 생성
-- =============================================

CREATE SEQUENCE USERS_SEQ         START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WITHDRAWN_SEQ     START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_ID_SEQ    START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_FILE_SEQ  START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WISH_SEQ          START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REVIEW_SEQ        START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHAT_ROOM     START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CHAT_SEQ          START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ  START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTI_SEQ          START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BANNER_SEQ        START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TAGS_SEQ          START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BOARD_SEQ         START WITH 1  INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================
-- 2. 테이블 생성
-- =============================================

-- 회원
CREATE TABLE USERS (
    USER_NO        NUMBER          NOT NULL,
    LOGIN_ID       VARCHAR2(50),
    PASS_WD        VARCHAR2(200),
    NAME           VARCHAR2(50)    NOT NULL,
    EMAIL          VARCHAR2(100),
    ROLE           VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    OAUTH_PROVIDER VARCHAR2(20),
    OAUTH_ID       VARCHAR2(100),
    IS_DELETED     CHAR(1)         DEFAULT 'N' NOT NULL,
    DELETED_AT     TIMESTAMP,
    REG_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO),
    CONSTRAINT CK_USERS_DELETED CHECK (IS_DELETED IN ('Y','N'))
);

-- 마이페이지 / 프로필
CREATE TABLE MY_USER_PAGE (
    USER_NO     NUMBER          NOT NULL,
    NICKNAME    VARCHAR2(30),
    PROFILE_IMG VARCHAR2(500)   DEFAULT 'default_profile.png',
    INTRODUCE   VARCHAR2(200)   DEFAULT '',
    TEMPERATURE NUMBER(4,1)     DEFAULT 36.5,
    CONSTRAINT PK_MY_USER_PAGE PRIMARY KEY (USER_NO),
    CONSTRAINT FK_MUP_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO)
);

-- 탈퇴 이력 (개인정보보호법 5년 보관)
CREATE TABLE WITHDRAWN_USERS (
    WITHDRAWN_ID   NUMBER          NOT NULL,
    USER_NO        NUMBER,
    LOGIN_ID       VARCHAR2(50),
    NAME           VARCHAR2(50),
    EMAIL          VARCHAR2(100),
    OAUTH_PROVIDER VARCHAR2(20),
    WITHDRAWN_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_WITHDRAWN PRIMARY KEY (WITHDRAWN_ID)
);

-- 대분류 카테고리
CREATE TABLE CATEGORY (
    CATEGORY_ID   NUMBER       NOT NULL,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

-- 소분류 카테고리
CREATE TABLE SUBCATEGORY (
    SUB_CATEGORY_ID    NUMBER       NOT NULL,
    SUB_CATEGORY_NAME  VARCHAR2(50) NOT NULL,
    PARENT_CATEGORY_ID NUMBER       NOT NULL,
    CONSTRAINT PK_SUBCATEGORY PRIMARY KEY (SUB_CATEGORY_ID),
    CONSTRAINT FK_SUBCATE_CATE FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

-- 상품
CREATE TABLE PRODUCT (
    PRODUCT_ID          NUMBER          NOT NULL,
    USER_NO             NUMBER          NOT NULL,
    PRODUCT_TITLE       VARCHAR2(200)   NOT NULL,
    SUB_CATEGORY_NAME   VARCHAR2(50),
    PRODUCT_PLACE       VARCHAR2(100),
    PRODUCT_STATE       VARCHAR2(20),
    PRODUCT_PRICE       NUMBER(15),
    PRODUCT_EXPLANATION CLOB,
    PRODUCT_KEYWORD     VARCHAR2(500),
    TRADE_STATUS        VARCHAR2(20)    DEFAULT 'SALE' NOT NULL,
    BUYER_NO            NUMBER,
    IS_DELETED          CHAR(1)         DEFAULT 'N' NOT NULL,
    DELETED_AT          TIMESTAMP,
    REG_DATE            DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_TRADE_STATUS CHECK (TRADE_STATUS IN ('SALE','RESERVED','SOLD')),
    CONSTRAINT CK_PRODUCT_DELETED CHECK (IS_DELETED IN ('Y','N'))
);

-- 상품 이미지
CREATE TABLE PRODUCT_FILE (
    FILE_ID       NUMBER           NOT NULL,
    PRODUCT_ID    NUMBER           NOT NULL,
    ORIGINAL_NAME VARCHAR2(500),
    SAVED_NAME    VARCHAR2(500),
    FILE_PATH     VARCHAR2(1000),
    IS_MAIN       NUMBER(1)        DEFAULT 0,
    CONSTRAINT PK_PRODUCT_FILE PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_PF_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- 찜 목록
CREATE TABLE WISHLIST (
    WISH_ID    NUMBER  NOT NULL,
    USER_NO    NUMBER  NOT NULL,
    PRODUCT_ID NUMBER  NOT NULL,
    CREATED_AT DATE    DEFAULT SYSDATE,
    CONSTRAINT PK_WISHLIST PRIMARY KEY (WISH_ID),
    CONSTRAINT FK_WISH_USER    FOREIGN KEY (USER_NO)    REFERENCES USERS(USER_NO),
    CONSTRAINT FK_WISH_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT UQ_WISH UNIQUE (USER_NO, PRODUCT_ID)
);

-- 거래 후기
CREATE TABLE REVIEW (
    REVIEW_ID   NUMBER          NOT NULL,
    PRODUCT_ID  NUMBER          NOT NULL,
    REVIEWER_NO NUMBER          NOT NULL,
    REVIEWEE_NO NUMBER          NOT NULL,
    RATING      NUMBER(1)       NOT NULL,
    CONTENT     VARCHAR2(1000),
    REG_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_REVIEW_REVIEWER FOREIGN KEY (REVIEWER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_REVIEW_REVIEWEE FOREIGN KEY (REVIEWEE_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_RATING CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT UQ_REVIEW UNIQUE (PRODUCT_ID, REVIEWER_NO)
);

-- 채팅방
CREATE TABLE CHAT_ROOM (
    ROOM_ID    NUMBER  NOT NULL,
    PRODUCT_ID NUMBER  NOT NULL,
    SELLER_NO  NUMBER  NOT NULL,
    BUYER_NO   NUMBER  NOT NULL,
    CREATED_AT DATE    DEFAULT SYSDATE,
    CONSTRAINT PK_CHAT_ROOM PRIMARY KEY (ROOM_ID),
    CONSTRAINT FK_CR_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_CR_SELLER  FOREIGN KEY (SELLER_NO)  REFERENCES USERS(USER_NO),
    CONSTRAINT FK_CR_BUYER   FOREIGN KEY (BUYER_NO)   REFERENCES USERS(USER_NO)
);

-- 채팅 메시지
CREATE TABLE CHAT_MESSAGE (
    MSG_ID      NUMBER          NOT NULL,
    ROOM_ID     NUMBER          NOT NULL,
    SENDER_NO   NUMBER          NOT NULL,
    MESSAGE     VARCHAR2(4000)  NOT NULL,
    SENT_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    IS_READ     CHAR(1)         DEFAULT 'N' NOT NULL,
    RECEIVER_NO NUMBER,
    CONSTRAINT PK_CHAT_MESSAGE PRIMARY KEY (MSG_ID),
    CONSTRAINT FK_CM_ROOM   FOREIGN KEY (ROOM_ID)   REFERENCES CHAT_ROOM(ROOM_ID),
    CONSTRAINT FK_CM_SENDER FOREIGN KEY (SENDER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_CM_READ CHECK (IS_READ IN ('Y','N'))
);

-- 알림
CREATE TABLE NOTIFICATION (
    NOTI_ID           VARCHAR2(20)  NOT NULL,
    USER_NO           NUMBER        NOT NULL,
    NOTI_MESSAGE      VARCHAR2(500),
    NOTI_URL          VARCHAR2(500),
    NOTIFICATION_TYPE VARCHAR2(30),
    IS_READ           CHAR(1)       DEFAULT 'N' NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTI_ID),
    CONSTRAINT FK_NOTI_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_NOTI_READ CHECK (IS_READ IN ('Y','N'))
);

-- 거래 이력 (SOLD 처리 시 1회 INSERT, 되돌릴 수 없음)
CREATE TABLE TRADE (
    PRODUCT_ID NUMBER    NOT NULL,
    SELLER_NO  NUMBER    NOT NULL,
    BUYER_NO   NUMBER    NOT NULL,
    TRADE_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_TRADE PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_TRADE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_TRADE_SELLER  FOREIGN KEY (SELLER_NO)  REFERENCES USERS(USER_NO),
    CONSTRAINT FK_TRADE_BUYER   FOREIGN KEY (BUYER_NO)   REFERENCES USERS(USER_NO)
);

-- 배너
CREATE TABLE BANNER (
    BANNER_ID  NUMBER         NOT NULL,
    IMAGE_URL  VARCHAR2(500)  NOT NULL,
    LINK_URL   VARCHAR2(500),
    SORT_ORDER NUMBER(3)      DEFAULT 0,
    IS_ACTIVE  CHAR(1)        DEFAULT 'Y' NOT NULL,
    START_DT   DATE,
    END_DT     DATE,
    REG_DATE   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_BANNER PRIMARY KEY (BANNER_ID),
    CONSTRAINT CK_BANNER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

-- 태그
CREATE TABLE TAGS (
    TAG_ID    NUMBER        NOT NULL,
    TAG_NAME  VARCHAR2(100) NOT NULL,
    USE_COUNT NUMBER(10)    DEFAULT 0,
    CONSTRAINT PK_TAGS PRIMARY KEY (TAG_ID),
    CONSTRAINT UQ_TAG_NAME UNIQUE (TAG_NAME)
);

-- 이메일 인증
CREATE TABLE EMAIL_AUTH (
    EMAIL       VARCHAR2(100)  NOT NULL,
    AUTH_CODE   VARCHAR2(10)   NOT NULL,
    CREATE_TIME TIMESTAMP      DEFAULT SYSTIMESTAMP,
    IS_VERIFIED CHAR(1)        DEFAULT 'N' NOT NULL,
    REQUEST_IP  VARCHAR2(50),
    CONSTRAINT PK_EMAIL_AUTH PRIMARY KEY (EMAIL),
    CONSTRAINT CK_EA_VERIFIED CHECK (IS_VERIFIED IN ('Y','N'))
);

-- 고객센터 게시판
CREATE TABLE BOARD (
    BOARD_NO       NUMBER          NOT NULL,
    BOARD_TITLE    VARCHAR2(200)   NOT NULL,
    BOARD_CONTENT  CLOB,
    BOARD_CATEGORY VARCHAR2(50),
    NOTICE_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    USER_NO        NUMBER,
    REG_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO),
    CONSTRAINT CK_NOTICE_YN CHECK (NOTICE_YN IN ('Y','N'))
);

-- =============================================
-- 3. 인덱스 생성
-- =============================================

CREATE INDEX IDX_PRODUCT_USER      ON PRODUCT(USER_NO);
CREATE INDEX IDX_PRODUCT_STATUS    ON PRODUCT(TRADE_STATUS, IS_DELETED);
CREATE INDEX IDX_PRODUCT_FILE_PID  ON PRODUCT_FILE(PRODUCT_ID);
CREATE INDEX IDX_WISHLIST_USER     ON WISHLIST(USER_NO);
CREATE INDEX IDX_CHAT_MSG_ROOM     ON CHAT_MESSAGE(ROOM_ID);
CREATE INDEX IDX_CHAT_MSG_RECEIVER ON CHAT_MESSAGE(RECEIVER_NO, IS_READ);
CREATE INDEX IDX_NOTI_USER         ON NOTIFICATION(USER_NO, IS_READ);
CREATE INDEX IDX_REVIEW_REVIEWEE   ON REVIEW(REVIEWEE_NO);

-- =============================================
-- 4. 기초 데이터 - 카테고리
-- =============================================

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, '디지털/가전');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, '의류/잡화');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, '가구/인테리어');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, '도서/음반');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, '스포츠/레저');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (6, '취미/게임');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (7, '뷰티/미용');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (8, '식물');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (9, '기타');

-- 디지털/가전 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (1,  '스마트폰',        1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (2,  '태블릿',          1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (3,  '노트북',          1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (4,  '데스크탑',        1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (5,  '카메라',          1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (6,  '이어폰/헤드폰',   1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (7,  'TV/모니터',       1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (8,  '게임기',          1);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (9,  '기타 디지털',     1);

-- 의류/잡화 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (10, '남성의류',        2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (11, '여성의류',        2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (12, '가방',            2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (13, '신발',            2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (14, '시계/주얼리',     2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (15, '모자/스카프',     2);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (16, '기타 의류',       2);

-- 가구/인테리어 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (17, '소파/거실가구',   3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (18, '침대/침실가구',   3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (19, '책상/서재가구',   3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (20, '수납/정리',       3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (21, '조명',            3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (22, '주방용품',        3);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (23, '기타 가구',       3);

-- 도서/음반 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (24, '소설/에세이',     4);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (25, '자기계발',        4);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (26, '전공/학습',       4);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (27, '만화/웹툰',       4);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (28, '음반/DVD',        4);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (29, '기타 도서',       4);

-- 스포츠/레저 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (30, '헬스/요가',       5);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (31, '자전거/킥보드',   5);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (32, '캠핑/등산',       5);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (33, '구기/라켓',       5);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (34, '수상스포츠',      5);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (35, '기타 스포츠',     5);

-- 취미/게임 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (36, '보드게임',        6);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (37, '피규어/완구',     6);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (38, '악기',            6);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (39, '미술/공예',       6);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (40, '게임 타이틀',     6);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (41, '기타 취미',       6);

-- 뷰티/미용 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (42, '스킨케어',        7);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (43, '메이크업',        7);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (44, '헤어케어',        7);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (45, '향수',            7);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (46, '기타 뷰티',       7);

-- 식물 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (47, '관엽식물',        8);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (48, '다육/선인장',     8);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (49, '씨앗/구근',       8);
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (50, '기타 식물',       8);

-- 기타 서브카테고리
INSERT INTO SUBCATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, PARENT_CATEGORY_ID) VALUES (51, '기타',            9);

COMMIT;

-- =============================================
-- 쿠폰
-- =============================================
CREATE SEQUENCE COUPON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_COUPON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE COUPON (
    COUPON_ID       NUMBER          PRIMARY KEY,
    NAME            VARCHAR2(100)   NOT NULL,
    TOTAL_COUNT     NUMBER          NOT NULL,
    REMAINING_COUNT NUMBER          NOT NULL,
    START_DATE      DATE,
    END_DATE        DATE,
    CREATED_AT      DATE            DEFAULT SYSDATE
);

CREATE TABLE USER_COUPON (
    USER_COUPON_ID  NUMBER  PRIMARY KEY,
    USER_ID         NUMBER  NOT NULL,
    COUPON_ID       NUMBER  NOT NULL,
    ISSUED_AT       DATE    DEFAULT SYSDATE,
    CONSTRAINT UK_USER_COUPON UNIQUE (USER_ID, COUPON_ID),
    CONSTRAINT FK_UC_USER    FOREIGN KEY (USER_ID)   REFERENCES USERS(USER_NO),
    CONSTRAINT FK_UC_COUPON  FOREIGN KEY (COUPON_ID) REFERENCES COUPON(COUPON_ID)
);

COMMIT;
