-- =============================================================
-- 니꺼내꺼 중고거래 플랫폼  Oracle DDL
-- 실행 순서: ① DROP → ② 시퀀스 → ③ 테이블 → ④ 인덱스 → ⑤ 샘플데이터
-- =============================================================


-- =============================================================
-- 1. 기존 객체 DROP (재실행 시 주석 해제 후 사용)
-- =============================================================
/*
DROP TABLE REVIEW           CASCADE CONSTRAINTS PURGE;
DROP TABLE TRADE            CASCADE CONSTRAINTS PURGE;
DROP TABLE WISHLIST         CASCADE CONSTRAINTS PURGE;
DROP TABLE EMAIL_AUTH       CASCADE CONSTRAINTS PURGE;
DROP TABLE NOTIFICATION     CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAT_MESSAGE     CASCADE CONSTRAINTS PURGE;
DROP TABLE CHAT_ROOM        CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT_FILE     CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT          CASCADE CONSTRAINTS PURGE;
DROP TABLE SUBCATEGORY      CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORY         CASCADE CONSTRAINTS PURGE;
DROP TABLE BOARD_COMMENT    CASCADE CONSTRAINTS PURGE;
DROP TABLE BOARD_FILE       CASCADE CONSTRAINTS PURGE;
DROP TABLE BOARD            CASCADE CONSTRAINTS PURGE;
DROP TABLE TAGS             CASCADE CONSTRAINTS PURGE;
DROP TABLE BANNER           CASCADE CONSTRAINTS PURGE;
DROP TABLE MY_USER_PAGE     CASCADE CONSTRAINTS PURGE;
DROP TABLE WITHDRAWN_USERS  CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS            CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE WITHDRAWN_SEQ;
DROP SEQUENCE PRODUCT_ID_SEQ;
DROP SEQUENCE PRODUCT_FILE_SEQ;
DROP SEQUENCE SEQ_CHAT_ROOM;
DROP SEQUENCE CHAT_MESSAGE_SEQ;
DROP SEQUENCE NOTI_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE BOARD_FILE_SEQ;
DROP SEQUENCE BOARD_COMMENT_SEQ;
DROP SEQUENCE BANNER_SEQ;
DROP SEQUENCE TAGS_SEQ;
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE SUBCATEGORY_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE WISH_SEQ;
*/


 DROP TABLE TRADE CASCADE CONSTRAINTS PURGE;
  DROP TABLE REVIEW CASCADE CONSTRAINTS PURGE;
  DROP TABLE EMAIL_AUTH CASCADE CONSTRAINTS PURGE;
  DROP TABLE TAGS CASCADE CONSTRAINTS PURGE;
  DROP TABLE BANNER CASCADE CONSTRAINTS PURGE;
  DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS PURGE;
  DROP TABLE BOARD_FILE CASCADE CONSTRAINTS PURGE;
  DROP TABLE BOARD CASCADE CONSTRAINTS PURGE;
  DROP TABLE NOTIFICATION CASCADE CONSTRAINTS PURGE;
  DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS PURGE;
  DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS PURGE;
  DROP TABLE WISHLIST CASCADE CONSTRAINTS PURGE;
  DROP TABLE PRODUCT_FILE CASCADE CONSTRAINTS PURGE;
  DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;
  DROP TABLE SUBCATEGORY CASCADE CONSTRAINTS PURGE;
  DROP TABLE CATEGORY CASCADE CONSTRAINTS PURGE;
  DROP TABLE MY_USER_PAGE CASCADE CONSTRAINTS PURGE;
  DROP TABLE WITHDRAWN_USERS CASCADE CONSTRAINTS PURGE;
  DROP TABLE USERS CASCADE CONSTRAINTS PURGE;


-- =============================================================
-- 2. 시퀀스 생성
-- =============================================================

CREATE SEQUENCE USERS_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WITHDRAWN_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_ID_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_FILE_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHAT_ROOM      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTI_SEQ           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BOARD_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CATEGORY_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUBCATEGORY_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REVIEW_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE WISH_SEQ           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- =============================================================
-- 3. 테이블 생성
-- =============================================================

-- -----------------------------------
-- 3-1. 회원
-- -----------------------------------
CREATE TABLE USERS (
    USER_NO        NUMBER          NOT NULL,
    LOGIN_ID       VARCHAR2(50),
    PASS_WD        VARCHAR2(200),
    NAME           VARCHAR2(50)    NOT NULL,
    EMAIL          VARCHAR2(100),
    ROLE           VARCHAR2(20)    DEFAULT 'ROLE_USER',
    OAUTH_PROVIDER VARCHAR2(20),
    OAUTH_ID       VARCHAR2(100),
    REG_DATE       DATE            DEFAULT SYSDATE,
    IS_DELETED     CHAR(1)         DEFAULT 'N' NOT NULL,
    DELETED_AT     TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_NO)
);

-- -----------------------------------
-- 3-2. 탈퇴 회원 보관 (개인정보보호법 5년)
-- -----------------------------------
CREATE TABLE WITHDRAWN_USERS (
    WITHDRAWN_ID   NUMBER          NOT NULL,
    USER_NO        NUMBER          NOT NULL,
    LOGIN_ID       VARCHAR2(50),
    NAME           VARCHAR2(50),
    EMAIL          VARCHAR2(100),
    OAUTH_PROVIDER VARCHAR2(20),
    WITHDRAWN_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
    PURGE_AT       DATE            DEFAULT ADD_MONTHS(SYSDATE, 60),
    CONSTRAINT PK_WITHDRAWN PRIMARY KEY (WITHDRAWN_ID)
);

-- -----------------------------------
-- 3-3. 마이페이지
-- -----------------------------------
CREATE TABLE MY_USER_PAGE (
    USER_NO     NUMBER          NOT NULL,
    PROFILE_IMG VARCHAR2(200)   DEFAULT 'default_profile.png',
    INTRODUCE   VARCHAR2(500)   DEFAULT '안녕하세요!',
    TEMPERATURE NUMBER(4,1)     DEFAULT 36.5,
    NICKNAME    VARCHAR2(50),
    CONSTRAINT PK_MYPAGE      PRIMARY KEY (USER_NO),
    CONSTRAINT FK_MYPAGE_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);
CREATE UNIQUE INDEX UQ_MYPAGE_NICKNAME ON MY_USER_PAGE (NICKNAME);

-- -----------------------------------
-- 3-4. 카테고리
-- -----------------------------------
CREATE TABLE CATEGORY (
    CATEGORY_ID   NUMBER       NOT NULL,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE SUBCATEGORY (
    SUB_CATEGORY_ID    NUMBER       NOT NULL,
    SUB_CATEGORY_NAME  VARCHAR2(50) NOT NULL,
    PARENT_CATEGORY_ID NUMBER       NOT NULL,
    CONSTRAINT PK_SUBCATEGORY          PRIMARY KEY (SUB_CATEGORY_ID),
    CONSTRAINT FK_SUBCATE_CATEGORY     FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

-- -----------------------------------
-- 3-5. 상품
-- -----------------------------------
CREATE TABLE PRODUCT (
    PRODUCT_ID          NUMBER          NOT NULL,
    USER_NO             NUMBER          NOT NULL,
    PRODUCT_TITLE       VARCHAR2(200)   NOT NULL,
    SUB_CATEGORY_NAME   VARCHAR2(50),
    PRODUCT_PLACE       VARCHAR2(100),
    PRODUCT_STATE       VARCHAR2(20),
    PRODUCT_PRICE       NUMBER          DEFAULT 0,
    PRODUCT_EXPLANATION VARCHAR2(2000),
    PRODUCT_KEYWORD     VARCHAR2(200),
    TRADE_STATUS        VARCHAR2(10)    DEFAULT 'SALE' NOT NULL,
    BUYER_NO            NUMBER,
    IS_DELETED          CHAR(1)         DEFAULT 'N' NOT NULL,
    DELETED_AT          TIMESTAMP,
    CONSTRAINT PK_PRODUCT       PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_USER  FOREIGN KEY (USER_NO)  REFERENCES USERS(USER_NO),
    CONSTRAINT FK_PRODUCT_BUYER FOREIGN KEY (BUYER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT CK_TRADE_STATUS  CHECK (TRADE_STATUS IN ('SALE','RESERVED','SOLD'))
);

-- -----------------------------------
-- 3-6. 상품 이미지
-- -----------------------------------
CREATE TABLE PRODUCT_FILE (
    FILE_ID       NUMBER        NOT NULL,
    PRODUCT_ID    NUMBER        NOT NULL,
    ORIGINAL_NAME VARCHAR2(200),
    SAVED_NAME    VARCHAR2(200),
    FILE_PATH     VARCHAR2(500),
    IS_MAIN       NUMBER(1)     DEFAULT 0,
    CONSTRAINT PK_PRODUCT_FILE  PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_PFILE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

-- -----------------------------------
-- 3-7. 찜
-- -----------------------------------
CREATE TABLE WISHLIST (
    WISH_ID    NUMBER  NOT NULL,
    USER_NO    NUMBER  NOT NULL,
    PRODUCT_ID NUMBER  NOT NULL,
    CREATED_AT DATE    DEFAULT SYSDATE,
    CONSTRAINT PK_WISHLIST      PRIMARY KEY (WISH_ID),
    CONSTRAINT FK_WISH_USER     FOREIGN KEY (USER_NO)    REFERENCES USERS(USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_WISH_PRODUCT  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_WISH          UNIQUE (USER_NO, PRODUCT_ID)
);

-- -----------------------------------
-- 3-8. 채팅방
-- -----------------------------------
CREATE TABLE CHAT_ROOM (
    ROOM_ID    NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    SELLER_NO  NUMBER NOT NULL,
    BUYER_NO   NUMBER NOT NULL,
    CREATED_AT DATE   DEFAULT SYSDATE,
    CONSTRAINT PK_CHAT_ROOM    PRIMARY KEY (ROOM_ID),
    CONSTRAINT FK_ROOM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_ROOM_SELLER  FOREIGN KEY (SELLER_NO)  REFERENCES USERS(USER_NO),
    CONSTRAINT FK_ROOM_BUYER   FOREIGN KEY (BUYER_NO)   REFERENCES USERS(USER_NO)
);

-- -----------------------------------
-- 3-9. 채팅 메시지
-- -----------------------------------
CREATE TABLE CHAT_MESSAGE (
    MSG_ID      NUMBER        NOT NULL,
    ROOM_ID     NUMBER        NOT NULL,
    SENDER_NO   NUMBER        NOT NULL,
    MESSAGE     VARCHAR2(2000),
    SENT_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
    IS_READ     VARCHAR2(1)   DEFAULT 'N',
    RECEIVER_NO NUMBER        NOT NULL,
    CONSTRAINT PK_CHAT_MESSAGE  PRIMARY KEY (MSG_ID),
    CONSTRAINT FK_MSG_ROOM      FOREIGN KEY (ROOM_ID)     REFERENCES CHAT_ROOM(ROOM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_SENDER    FOREIGN KEY (SENDER_NO)   REFERENCES USERS(USER_NO),
    CONSTRAINT FK_MSG_RECEIVER  FOREIGN KEY (RECEIVER_NO) REFERENCES USERS(USER_NO)
);

-- -----------------------------------
-- 3-10. 알림
-- -----------------------------------
CREATE TABLE NOTIFICATION (
    NOTI_ID           VARCHAR2(10)  NOT NULL,
    USER_NO           NUMBER        NOT NULL,
    NOTI_MESSAGE      VARCHAR2(500),
    NOTI_URL          VARCHAR2(200),
    IS_READ           VARCHAR2(1)   DEFAULT 'N',
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
    NOTIFICATION_TYPE VARCHAR2(20),
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTI_ID),
    CONSTRAINT FK_NOTI_USER    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);

-- -----------------------------------
-- 3-11. 게시판
-- -----------------------------------
CREATE TABLE BOARD (
    BOARD_NO                 NUMBER        NOT NULL,
    BOARD_WRITER             VARCHAR2(50),
    BOARD_TITLE              VARCHAR2(200) NOT NULL,
    BOARD_CONTENT            VARCHAR2(2000),
    BOARD_DATE               DATE          DEFAULT SYSDATE,
    BOARD_CATEGORY           VARCHAR2(50),
    NOTICE_YN                VARCHAR2(1)   DEFAULT 'N',
    BOARD_ORIGINAL_FILE_NAME VARCHAR2(200),
    BOARD_RENAMED_FILE_NAME  VARCHAR2(200),
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO)
);

-- -----------------------------------
-- 3-11-1. 게시판 첨부파일
-- -----------------------------------
CREATE TABLE BOARD_FILE (
    FILE_NO        NUMBER        NOT NULL,
    BOARD_NO       NUMBER        NOT NULL,
    BOARD_FILE_NAME VARCHAR2(200),
    CONSTRAINT PK_BOARD_FILE   PRIMARY KEY (FILE_NO),
    CONSTRAINT FK_BFILE_BOARD  FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);
CREATE SEQUENCE BOARD_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- -----------------------------------
-- 3-11-2. 게시판 댓글
-- -----------------------------------
CREATE TABLE BOARD_COMMENT (
    COMMENT_NO      NUMBER        NOT NULL,
    COMMENT_WRITER  VARCHAR2(50),
    BOARD_NO        NUMBER        NOT NULL,
    COMMENT_NO_FK   NUMBER,
    COMMENT_DATE    DATE          DEFAULT SYSDATE,
    COMMENT_CONTENT VARCHAR2(1000),
    CONSTRAINT PK_BOARD_COMMENT  PRIMARY KEY (COMMENT_NO),
    CONSTRAINT FK_COMMENT_BOARD  FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);
CREATE SEQUENCE BOARD_COMMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- -----------------------------------
-- 3-12. 배너
-- -----------------------------------
CREATE TABLE BANNER (
    BANNER_ID  NUMBER        NOT NULL,
    IMAGE_URL  VARCHAR2(500) NOT NULL,
    LINK_URL   VARCHAR2(500),
    SORT_ORDER NUMBER        DEFAULT 0,
    IS_ACTIVE  CHAR(1)       DEFAULT 'Y' NOT NULL,
    START_DT   DATE,
    END_DT     DATE,
    REG_DATE   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_BANNER PRIMARY KEY (BANNER_ID)
);
CREATE SEQUENCE BANNER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- -----------------------------------
-- 3-13. 태그 (Elasticsearch 동기화용)
-- -----------------------------------
CREATE TABLE TAGS (
    TAG_ID    NUMBER        NOT NULL,
    TAG_NAME  VARCHAR2(100) NOT NULL,
    USE_COUNT NUMBER        DEFAULT 0,
    CONSTRAINT PK_TAGS    PRIMARY KEY (TAG_ID),
    CONSTRAINT UQ_TAG_NAME UNIQUE (TAG_NAME)
);
CREATE SEQUENCE TAGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- -----------------------------------
-- 3-15. 이메일 인증
-- -----------------------------------
CREATE TABLE EMAIL_AUTH (
    EMAIL       VARCHAR2(100) NOT NULL,
    AUTH_CODE   VARCHAR2(10)  NOT NULL,
    CREATE_TIME TIMESTAMP     DEFAULT SYSTIMESTAMP,
    IS_VERIFIED VARCHAR2(1)   DEFAULT 'N',
    REQUEST_IP  VARCHAR2(50),
    CONSTRAINT PK_EMAIL_AUTH PRIMARY KEY (EMAIL)
);

-- -----------------------------------
-- 3-16. 리뷰
-- -----------------------------------
CREATE TABLE REVIEW (
    REVIEW_ID   NUMBER        NOT NULL,
    PRODUCT_ID  NUMBER        NOT NULL,
    REVIEWER_NO NUMBER        NOT NULL,
    REVIEWEE_NO NUMBER        NOT NULL,
    RATING      NUMBER(1)     NOT NULL,
    CONTENT     VARCHAR2(500),
    REG_DATE    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_REVIEW          PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_REVIEW_WRITER   FOREIGN KEY (REVIEWER_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT FK_REVIEW_TARGET   FOREIGN KEY (REVIEWEE_NO) REFERENCES USERS(USER_NO),
    CONSTRAINT UQ_REVIEW_PRODUCT  UNIQUE (PRODUCT_ID, REVIEWER_NO),
    CONSTRAINT CK_RATING          CHECK (RATING BETWEEN 1 AND 5)
);

-- -----------------------------------
-- 3-17. 거래 이력
-- -----------------------------------
CREATE TABLE TRADE (
    TRADE_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL UNIQUE,
    SELLER_NO  NUMBER NOT NULL,
    BUYER_NO   NUMBER,
    TRADE_DATE DATE   DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_TRADE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_TRADE_SELLER  FOREIGN KEY (SELLER_NO)  REFERENCES USERS(USER_NO),
    CONSTRAINT FK_TRADE_BUYER   FOREIGN KEY (BUYER_NO)   REFERENCES USERS(USER_NO)
);


-- =============================================================
-- 4. 인덱스 생성
-- =============================================================

-- USERS
CREATE INDEX IDX_USERS_LOGIN_ID ON USERS (LOGIN_ID);
CREATE INDEX IDX_USERS_EMAIL    ON USERS (EMAIL);
CREATE INDEX IDX_USERS_OAUTH    ON USERS (OAUTH_ID, OAUTH_PROVIDER);

-- PRODUCT
CREATE INDEX IDX_PRODUCT_USER    ON PRODUCT (USER_NO);
CREATE INDEX IDX_PRODUCT_SUBCATE ON PRODUCT (SUB_CATEGORY_NAME);
CREATE INDEX IDX_PRODUCT_TITLE   ON PRODUCT (PRODUCT_TITLE);
CREATE INDEX IDX_PRODUCT_BUYER   ON PRODUCT (BUYER_NO);

-- PRODUCT_FILE
CREATE INDEX IDX_PFILE_PRODUCT ON PRODUCT_FILE (PRODUCT_ID);
CREATE INDEX IDX_PFILE_MAIN    ON PRODUCT_FILE (PRODUCT_ID, IS_MAIN);

-- WISHLIST
CREATE INDEX IDX_WISH_USER    ON WISHLIST (USER_NO);
CREATE INDEX IDX_WISH_PRODUCT ON WISHLIST (PRODUCT_ID);

-- CHAT_ROOM
CREATE INDEX IDX_ROOM_SELLER  ON CHAT_ROOM (SELLER_NO);
CREATE INDEX IDX_ROOM_BUYER   ON CHAT_ROOM (BUYER_NO);
CREATE INDEX IDX_ROOM_PRODUCT ON CHAT_ROOM (PRODUCT_ID);

-- CHAT_MESSAGE
CREATE INDEX IDX_MSG_ROOM     ON CHAT_MESSAGE (ROOM_ID);
CREATE INDEX IDX_MSG_RECEIVER ON CHAT_MESSAGE (RECEIVER_NO, IS_READ);
CREATE INDEX IDX_MSG_SENT     ON CHAT_MESSAGE (ROOM_ID, SENT_AT);

-- NOTIFICATION
CREATE INDEX IDX_NOTI_USER ON NOTIFICATION (USER_NO, IS_READ);
CREATE INDEX IDX_NOTI_TYPE ON NOTIFICATION (USER_NO, NOTIFICATION_TYPE);

-- REVIEW
CREATE INDEX IDX_REVIEW_REVIEWEE ON REVIEW (REVIEWEE_NO);

-- BOARD
CREATE INDEX IDX_BOARD_NOTICE   ON BOARD (NOTICE_YN, BOARD_NO);
CREATE INDEX IDX_BOARD_CATEGORY ON BOARD (BOARD_CATEGORY);

-- BOARD_FILE / BOARD_COMMENT
CREATE INDEX IDX_BFILE_BOARD   ON BOARD_FILE    (BOARD_NO);
CREATE INDEX IDX_COMMENT_BOARD ON BOARD_COMMENT (BOARD_NO);

-- BANNER
CREATE INDEX IDX_BANNER_ACTIVE ON BANNER (IS_ACTIVE, START_DT, END_DT);

-- TAGS
CREATE INDEX IDX_TAGS_USECOUNT ON TAGS (USE_COUNT DESC);

-- EMAIL_AUTH
CREATE INDEX IDX_EMAIL_TIME ON EMAIL_AUTH (EMAIL, CREATE_TIME);


-- =============================================================
-- 5. 샘플 데이터
-- =============================================================

-- 5-1. 회원 (비밀번호: hifive1234 / admin1234)
INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'hong01', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '홍길동', 'hong01@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'kim02', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '김철수', 'kim02@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'lee03', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '이영희', 'lee03@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, NAME, EMAIL, ROLE, OAUTH_PROVIDER, OAUTH_ID, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, '박민준', 'park04@kakao.com', 'ROLE_USER', 'kakao', '3012345678', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'choi05', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '최수진', 'choi05@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'jung06', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '정대현', 'jung06@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, NAME, EMAIL, ROLE, OAUTH_PROVIDER, OAUTH_ID, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, '강지원', 'kang07@kakao.com', 'ROLE_USER', 'kakao', '3087654321', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'yoon08', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '윤서연', 'yoon08@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'lim09', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhy', '임태양', 'lim09@email.com', 'ROLE_USER', SYSDATE);

INSERT INTO USERS (USER_NO, LOGIN_ID, PASS_WD, NAME, EMAIL, ROLE, REG_DATE)
VALUES (USERS_SEQ.NEXTVAL, 'admin', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', '관리자', 'admin@hifive.com', 'ROLE_ADMIN', SYSDATE);


-- 5-2. 마이페이지 (USER_NO 1~10)
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (1,  'default_profile.png', '안녕하세요, 홍길동입니다. 깔끔하게 거래해요!',    36.5);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (2,  'default_profile.png', '빠른 거래 선호합니다. 잘 부탁드려요.',            37.2);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (3,  'default_profile.png', '친절한 거래 환경 만들어가겠습니다 :)',             38.0);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (4,  'default_profile.png', '카카오로 로그인한 박민준입니다.',                  36.5);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (5,  'default_profile.png', '좋은 물건 좋은 가격에 드립니다!',                  37.8);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (6,  'default_profile.png', '성실하게 거래합니다. 연락주세요.',                  36.5);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (7,  'default_profile.png', '강지원입니다. 소통 잘해요!',                       39.0);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (8,  'default_profile.png', '믿을 수 있는 판매자가 되겠습니다.',                 36.5);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (9,  'default_profile.png', '직거래 선호합니다. 서울 강남 근처.',               36.8);
INSERT INTO MY_USER_PAGE (USER_NO, PROFILE_IMG, INTRODUCE, TEMPERATURE) VALUES (10, 'default_profile.png', '니꺼내꺼 관리자 계정입니다.',                      40.0);


-- 5-3. 카테고리
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '패션의류');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '패션잡화');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '가전제품');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, 'PC/모바일');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '가구/인테리어');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '리빙/생활');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '스포츠/레저');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '도서/음반/문구');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (CATEGORY_SEQ.NEXTVAL, '차량/오토바이');


-- 5-4. 서브카테고리
-- 패션의류(1)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '남성의류',   1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '여성의류',   1);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '아동의류',   1);
-- 패션잡화(2)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '가방',       2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '신발',       2);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '시계/주얼리', 2);
-- 가전제품(3)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, 'TV/영상',    3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '냉장고',     3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '세탁기',     3);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '에어컨',     3);
-- PC/모바일(4)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '스마트폰',   4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '노트북',     4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '태블릿',     4);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '데스크탑',   4);
-- 가구/인테리어(5)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '소파/침대',  5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '책상/의자',  5);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '수납/정리',  5);
-- 리빙/생활(6)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '주방용품',   6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '욕실용품',   6);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '청소용품',   6);
-- 스포츠/레저(7)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '운동용품',   7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '자전거',     7);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '캠핑',       7);
-- 도서/음반/문구(8)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '도서',       8);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '음반/DVD',   8);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '문구/취미',  8);
-- 차량/오토바이(9)
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '자동차',     9);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '오토바이',   9);
INSERT INTO SUBCATEGORY VALUES (SUBCATEGORY_SEQ.NEXTVAL, '자동차용품', 9);

COMMIT;
