-- =============================================
-- TAGS 테이블 DDL
-- =============================================
CREATE TABLE TAGS (
    TAG_ID    NUMBER PRIMARY KEY,
    TAG_NAME  VARCHAR2(50) NOT NULL UNIQUE,
    USE_COUNT NUMBER DEFAULT 0 NOT NULL
);

CREATE SEQUENCE TAGS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- =============================================
-- 초기 태그 데이터 (중고거래 컨셉, 250개+)
-- USE_COUNT : 인기도 반영 (검색 상위 노출용)
-- =============================================

-- ===== 패션 / 의류 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#패션', 980);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#의류', 870);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#남성의류', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#여성의류', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#자켓', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#코트', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가디건', 390);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#청바지', 610);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#티셔츠', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#후드티', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#맨투맨', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#니트', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#원피스', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스커트', 370);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#슬랙스', 310);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#패딩', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#점퍼', 440);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#블라우스', 280);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#셔츠', 350);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#반팔', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#긴팔', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#조거팬츠', 320);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#레깅스', 290);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#트레이닝복', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#수영복', 150);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#잠옷', 200);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#정장', 330);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#명품의류', 410);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#빈티지의류', 360);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#미개봉의류', 270);

-- ===== 신발 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#신발', 860);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#운동화', 790);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#나이키', 920);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아디다스', 880);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#뉴발란스', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#컨버스', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#반스', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#구두', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#슬리퍼', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#부츠', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#샌들', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스니커즈', 840);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#로퍼', 270);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#하이힐', 220);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#크록스', 460);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#나이키에어맥스', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#조던', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#나이키덩크', 650);

-- ===== 가방 / 악세서리 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가방', 830);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#백팩', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#크로스백', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#토트백', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#숄더백', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#클러치', 310);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#지갑', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#카드지갑', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#명품가방', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#루이비통', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#구찌', 610);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#샤넬', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#프라다', 530);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#시계', 870);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#손목시계', 740);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#목걸이', 460);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#반지', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#귀걸이', 350);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#팔찌', 300);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#선글라스', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#모자', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#벨트', 290);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스카프', 230);

-- ===== 스마트폰 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스마트폰', 990);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이폰', 1050);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이폰15', 880);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이폰14', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이폰13', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시', 950);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시S24', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시S23', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시폴드', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시플립', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#중고폰', 890);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#공기계', 740);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#무약정폰', 530);

-- ===== 태블릿 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#태블릿', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이패드', 850);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이패드프로', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이패드에어', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시탭', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시탭S9', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#애플펜슬', 610);

-- ===== 노트북 / 컴퓨터 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#노트북', 980);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#맥북', 920);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#맥북프로', 850);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#맥북에어', 790);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#M1맥북', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#M2맥북', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#LG그램', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#삼성노트북', 630);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#게이밍노트북', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#데스크탑', 670);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#조립PC', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#맥미니', 390);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#iMac', 420);

-- ===== 컴퓨터 주변기기 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#모니터', 870);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#키보드', 840);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#마우스', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#기계식키보드', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#무선마우스', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#웹캠', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#SSD', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#RAM', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#그래픽카드', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#RTX4090', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#RTX4080', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#RTX3080', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#CPU', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#메인보드', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#파워서플라이', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#USB허브', 370);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#외장하드', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#NAS', 320);

-- ===== 이어폰 / 오디오 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#에어팟', 960);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#에어팟프로', 890);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#에어팟맥스', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#이어폰', 840);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#무선이어폰', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#헤드셋', 670);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#헤드폰', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#블루투스스피커', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#갤럭시버즈', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#소니이어폰', 530);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#보스헤드폰', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#유선이어폰', 380);

-- ===== 카메라 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#카메라', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#DSLR', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#미러리스', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#소니카메라', 630);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#캐논카메라', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#니콘카메라', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#후지필름', 460);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#카메라렌즈', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#삼각대', 390);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#액션캠', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#고프로', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#드론', 550);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#필름카메라', 370);

-- ===== 게임 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#게임', 870);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#플레이스테이션', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#PS5', 950);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#PS4', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#닌텐도스위치', 900);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#닌텐도', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#Xbox', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#게임CD', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#게임기', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#포켓몬카드', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#레트로게임', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스팀덱', 520);

-- ===== 가전제품 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가전', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#에어컨', 850);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#냉장고', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#세탁기', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#건조기', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#식기세척기', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#청소기', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#로봇청소기', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#다이슨청소기', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전자레인지', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#에어프라이어', 810);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#공기청정기', 740);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#제습기', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가습기', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#선풍기', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#TV', 870);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#OLED TV', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#빔프로젝터', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#안마의자', 470);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#커피머신', 610);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#밥솥', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#믹서기', 320);

-- ===== 가구 / 인테리어 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가구', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#소파', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#책상', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#의자', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#게이밍체어', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#침대', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#매트리스', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#서랍장', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#옷장', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#책장', 390);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#식탁', 440);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#조명', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스탠드조명', 370);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#커튼', 280);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#러그', 320);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#이케아가구', 550);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스탠딩책상', 480);

-- ===== 도서 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#도서', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#소설', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#자기계발서', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#만화책', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#수험서', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전공서적', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#영어책', 460);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#어린이책', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#그림책', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#요리책', 310);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#경제경영서', 550);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#잡지', 270);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#사진집', 290);

-- ===== 스포츠 / 레저 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스포츠', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#자전거', 840);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#킥보드', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전동킥보드', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#캠핑', 920);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#텐트', 750);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#캠핑의자', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#캠핑테이블', 510);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#랜턴', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#등산', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#등산화', 630);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#등산배낭', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#낚시', 670);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#낚시대', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#골프', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#골프채', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#골프백', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#헬스기구', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#덤벨', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#바벨', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#요가매트', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#러닝머신', 610);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#서핑보드', 310);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스키장비', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#보드복', 340);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#인라인스케이트', 290);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#배드민턴', 450);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#테니스라켓', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#축구공', 360);

-- ===== 취미 / 수집 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#레고', 850);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#피규어', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#건프라', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#보드게임', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#퍼즐', 470);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#다이캐스트', 350);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#수집품', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#한정판', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#굿즈', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아이돌굿즈', 810);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#앨범', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#포토카드', 760);

-- ===== 악기 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#악기', 640);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#기타', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#어쿠스틱기타', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#일렉기타', 530);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#베이스기타', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#피아노', 620);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전자피아노', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#드럼', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전자드럼', 440);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#우쿨렐레', 350);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#바이올린', 320);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#앰프', 390);

-- ===== 유아 / 아동 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#유아용품', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아동의류', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#장난감', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#유모차', 590);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#카시트', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아기침대', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#바운서', 360);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#아기띠', 410);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#학습교재', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#블록장난감', 520);

-- ===== 반려동물 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#반려동물', 710);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#강아지용품', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#고양이용품', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#펫케어', 480);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#캣타워', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#강아지옷', 390);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#펫하우스', 360);

-- ===== 뷰티 / 미용 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#뷰티', 690);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#화장품', 720);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#향수', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#스킨케어', 630);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#헤어드라이기', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#고데기', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#면도기', 410);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#전동칫솔', 450);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#미용기기', 530);

-- ===== 차량 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#차량용품', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#블랙박스', 810);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#네비게이션', 680);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#카시트', 540);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#자동차부품', 460);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#타이어', 520);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#오디오', 430);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#하이패스', 380);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#차량매트', 310);

-- ===== 식물 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#식물', 560);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#화분', 490);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#다육식물', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#선인장', 350);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#공기정화식물', 380);

-- ===== 기타 =====
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#미개봉', 850);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#새상품', 780);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#정품', 730);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#한정판', 650);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#단품', 420);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#풀박스', 580);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#직거래', 890);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#택배거래', 820);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#급처', 760);
INSERT INTO TAGS VALUES (TAGS_SEQ.NEXTVAL, '#가격협의', 680);

COMMIT;
