-- =============================================================
-- 테스트 데이터: 유저 37(카카오, 판매자) → 유저 38(일반, 구매자)
-- 상품 10개 거래완료 기준 (채팅, 리뷰, 거래내역 포함)
-- SQL Developer 에서 전체 선택 후 실행
-- =============================================================

DECLARE
  -- 상품 ID
  p1  NUMBER; p2  NUMBER; p3  NUMBER; p4  NUMBER; p5  NUMBER;
  p6  NUMBER; p7  NUMBER; p8  NUMBER; p9  NUMBER; p10 NUMBER;

  -- 채팅방 ID
  r1  NUMBER; r2  NUMBER; r3  NUMBER; r4  NUMBER; r5  NUMBER;
  r6  NUMBER; r7  NUMBER; r8  NUMBER; r9  NUMBER; r10 NUMBER;

BEGIN

  /* ============================================================
     1. PRODUCT (판매자 37, 구매자 38, 전부 SOLD)
     ============================================================ */
  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '아이폰 14 Pro 128GB 딥퍼플', '스마트폰', '서울 강남구', '거의새것', 850000,
          '아이폰 14 Pro 128GB 딥퍼플입니다. 사용 기간 4개월, 외관 흠집 전혀 없습니다. 케이스 포함 판매합니다.',
          '아이폰,iPhone,애플,스마트폰', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p1;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '에어팟 프로 2세대 USB-C', '스마트폰', '서울 강남구', '거의새것', 230000,
          '에어팟 프로 2세대 USB-C 타입입니다. 5개월 사용, 배터리 95% 이상. 정품 케이스 포함.',
          '에어팟,AirPods,애플,무선이어폰', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p2;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '닌텐도 스위치 OLED 화이트 풀구성', '스마트폰', '서울 서초구', '거의새것', 320000,
          '닌텐도 스위치 OLED 화이트입니다. 6개월 사용, 스크린 흠집 없음. 독, 조이콘, 충전케이블 모두 포함.',
          '닌텐도,스위치,Switch,OLED,게임기', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p3;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '소니 WF-1000XM5 블루투스 이어폰', 'TV/영상', '서울 강남구', '거의새것', 195000,
          '소니 WF-1000XM5 노이즈캔슬링 무선이어폰입니다. 구입 3개월, 배터리 정상. 파우치 포함.',
          '소니,Sony,이어폰,노이즈캔슬링,무선이어폰', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p4;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '나이키 에어맥스 90 화이트 270mm', '신발', '서울 강남구', '거의새것', 68000,
          '나이키 에어맥스 90 화이트 270mm입니다. 총 3회 착용. 박스 포함 판매합니다.',
          '나이키,Nike,에어맥스,운동화,스니커즈', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p5;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '무인양품 캐리어 46L 네이비', '수납/정리', '서울 강남구', '중고', 55000,
          '무지 캐리어 46L 네이비입니다. 2년 사용, 바퀴 이상 없음. 기내 반입 가능 사이즈.',
          '무인양품,MUJI,캐리어,여행가방', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p6;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '다이슨 에어랩 컴플리트 롱 골드', '청소용품', '서울 강남구', '거의새것', 480000,
          '다이슨 에어랩 컴플리트 롱 골드입니다. 구입 2개월, 거의 사용 안 했습니다. 모든 어태치먼트 포함.',
          '다이슨,Dyson,에어랩,드라이기,헤어스타일러', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p7;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '스탠리 퀜처 텀블러 1.18L 크림', '주방용품', '서울 서초구', '거의새것', 38000,
          '스탠리 퀜처 텀블러 1.18L 크림 색상입니다. 2회 사용. 흠집 없이 깨끗합니다.',
          '스탠리,Stanley,텀블러,보온병,퀜처', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p8;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '맥북 프로 14인치 M3 스페이스블랙', '노트북', '서울 강남구', '거의새것', 2200000,
          '맥북 프로 14인치 M3 스페이스블랙 18GB RAM 512GB입니다. 구입 2개월, 외관 흠집 없음. 충전기 포함.',
          '맥북,MacBook,애플,노트북,M3', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p9;

  INSERT INTO PRODUCT (PRODUCT_ID, USER_NO, PRODUCT_TITLE, SUB_CATEGORY_NAME, PRODUCT_PLACE, PRODUCT_STATE, PRODUCT_PRICE, PRODUCT_EXPLANATION, PRODUCT_KEYWORD, TRADE_STATUS, BUYER_NO, IS_DELETED)
  VALUES (PRODUCT_ID_SEQ.NEXTVAL, 37, '레고 테크닉 포르쉐 911 42096', '문구/취미', '서울 강남구', '신상', 92000,
          '레고 테크닉 포르쉐 911 42096 미개봉 새제품입니다. 선물용으로 구매했으나 중복 선물로 판매합니다.',
          '레고,LEGO,테크닉,포르쉐,장난감', 'SOLD', 38, 'N')
  RETURNING PRODUCT_ID INTO p10;


  /* ============================================================
     2. PRODUCT_FILE (각 상품 대표 이미지 1장 - 공통 플레이스홀더)
     ============================================================ */
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p1,  'iphone14pro.jpg',  'iphone14pro.jpg',  '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p2,  'airpodspro2.jpg',  'airpodspro2.jpg',  '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p3,  'switch_oled.jpg',  'switch_oled.jpg',  '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p4,  'sony_xm5.jpg',     'sony_xm5.jpg',     '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p5,  'nike_am90.jpg',    'nike_am90.jpg',    '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p6,  'muji_luggage.jpg', 'muji_luggage.jpg', '/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p7,  'dyson_airwrap.jpg','dyson_airwrap.jpg','/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p8,  'stanley_tumbler.jpg','stanley_tumbler.jpg','/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p9,  'macbook_pro14.jpg','macbook_pro14.jpg','/images/common/hifiveLogo.png', 1);
  INSERT INTO PRODUCT_FILE (FILE_ID, PRODUCT_ID, ORIGINAL_NAME, SAVED_NAME, FILE_PATH, IS_MAIN)
  VALUES (PRODUCT_FILE_SEQ.NEXTVAL, p10, 'lego_porsche.jpg', 'lego_porsche.jpg', '/images/common/hifiveLogo.png', 1);


  /* ============================================================
     3. CHAT_ROOM (상품별 1개 채팅방, 판매자=37 / 구매자=38)
     ============================================================ */
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p1,  37, 38) RETURNING ROOM_ID INTO r1;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p2,  37, 38) RETURNING ROOM_ID INTO r2;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p3,  37, 38) RETURNING ROOM_ID INTO r3;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p4,  37, 38) RETURNING ROOM_ID INTO r4;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p5,  37, 38) RETURNING ROOM_ID INTO r5;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p6,  37, 38) RETURNING ROOM_ID INTO r6;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p7,  37, 38) RETURNING ROOM_ID INTO r7;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p8,  37, 38) RETURNING ROOM_ID INTO r8;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p9,  37, 38) RETURNING ROOM_ID INTO r9;
  INSERT INTO CHAT_ROOM (ROOM_ID, PRODUCT_ID, SELLER_NO, BUYER_NO) VALUES (SEQ_CHAT_ROOM.NEXTVAL, p10, 37, 38) RETURNING ROOM_ID INTO r10;


  /* ============================================================
     4. CHAT_MESSAGE (방별 3~4건, 모두 IS_READ='Y')
        SENDER_NO / RECEIVER_NO: 38↔37
     ============================================================ */
  -- Room 1 (아이폰 14 Pro)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r1, 38, '안녕하세요! 아이폰 아직 판매 중인가요?', SYSTIMESTAMP - INTERVAL '10' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r1, 37, '네 판매 중입니다! 케이스도 같이 드려요 :)', SYSTIMESTAMP - INTERVAL '10' DAY + INTERVAL '5' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r1, 38, '직거래 가능한가요? 강남 쪽 되시나요?', SYSTIMESTAMP - INTERVAL '10' DAY + INTERVAL '10' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r1, 37, '네 강남역 근처 직거래 가능합니다. 내일 오후 어떠세요?', SYSTIMESTAMP - INTERVAL '10' DAY + INTERVAL '15' MINUTE, 'Y', 38);

  -- Room 2 (에어팟 프로)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r2, 38, '에어팟 프로 배터리 상태 어떻게 되나요?', SYSTIMESTAMP - INTERVAL '9' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r2, 37, '본체 95%, 케이스 92% 정도입니다!', SYSTIMESTAMP - INTERVAL '9' DAY + INTERVAL '3' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r2, 38, '좋네요. 가격 조금만 네고 가능할까요?', SYSTIMESTAMP - INTERVAL '9' DAY + INTERVAL '8' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r2, 37, '220000원에 드릴게요!', SYSTIMESTAMP - INTERVAL '9' DAY + INTERVAL '12' MINUTE, 'Y', 38);

  -- Room 3 (닌텐도 스위치)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r3, 38, '스위치 OLED 게임팩 포함되나요?', SYSTIMESTAMP - INTERVAL '8' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r3, 37, '본체+독+조이콘+충전케이블만 포함입니다. 게임팩은 없어요!', SYSTIMESTAMP - INTERVAL '8' DAY + INTERVAL '4' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r3, 38, '알겠습니다, 구매하겠습니다!', SYSTIMESTAMP - INTERVAL '8' DAY + INTERVAL '9' MINUTE, 'Y', 37);

  -- Room 4 (소니 이어폰)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r4, 38, '소니 이어폰 노이즈캔슬링 잘 되나요?', SYSTIMESTAMP - INTERVAL '7' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r4, 37, '네 정말 잘 됩니다. 지하철에서 완전 차단돼요!', SYSTIMESTAMP - INTERVAL '7' DAY + INTERVAL '6' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r4, 38, '좋아요! 택배 거래 가능할까요?', SYSTIMESTAMP - INTERVAL '7' DAY + INTERVAL '11' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r4, 37, '네 택배 가능합니다. 안전하게 포장해서 보내드릴게요!', SYSTIMESTAMP - INTERVAL '7' DAY + INTERVAL '15' MINUTE, 'Y', 38);

  -- Room 5 (나이키 에어맥스)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r5, 38, '운동화 사이즈가 270mm 맞죠?', SYSTIMESTAMP - INTERVAL '6' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r5, 37, '네 270mm 맞아요! 발볼 좁은 편이에요.', SYSTIMESTAMP - INTERVAL '6' DAY + INTERVAL '5' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r5, 38, '구매하겠습니다!', SYSTIMESTAMP - INTERVAL '6' DAY + INTERVAL '10' MINUTE, 'Y', 37);

  -- Room 6 (무인양품 캐리어)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r6, 38, '캐리어 바퀴 소리는 어떤가요?', SYSTIMESTAMP - INTERVAL '5' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r6, 37, '아주 조용하고 부드럽게 잘 굴러갑니다!', SYSTIMESTAMP - INTERVAL '5' DAY + INTERVAL '7' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r6, 38, '네고 조금 부탁드려요~', SYSTIMESTAMP - INTERVAL '5' DAY + INTERVAL '13' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r6, 37, '50000원에 가능합니다!', SYSTIMESTAMP - INTERVAL '5' DAY + INTERVAL '18' MINUTE, 'Y', 38);

  -- Room 7 (다이슨 에어랩)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r7, 38, '에어랩 어태치먼트 몇 개 포함인가요?', SYSTIMESTAMP - INTERVAL '4' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r7, 37, '컴플리트 풀구성이라 전체 다 포함입니다!', SYSTIMESTAMP - INTERVAL '4' DAY + INTERVAL '4' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r7, 38, '와 대박이다. 바로 구매할게요!', SYSTIMESTAMP - INTERVAL '4' DAY + INTERVAL '8' MINUTE, 'Y', 37);

  -- Room 8 (스탠리 텀블러)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r8, 38, '텀블러 크림 색상 실제로 보면 어떤가요?', SYSTIMESTAMP - INTERVAL '3' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r8, 37, '아이보리에 가까운 크림색이에요. 사진이랑 거의 같아요!', SYSTIMESTAMP - INTERVAL '3' DAY + INTERVAL '6' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r8, 38, '택배로 구매하겠습니다!', SYSTIMESTAMP - INTERVAL '3' DAY + INTERVAL '11' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r8, 37, '네 꼼꼼하게 포장해서 보내드릴게요!', SYSTIMESTAMP - INTERVAL '3' DAY + INTERVAL '14' MINUTE, 'Y', 38);

  -- Room 9 (맥북 프로 14)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r9, 38, '맥북 배터리 사이클 몇 번인가요?', SYSTIMESTAMP - INTERVAL '2' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r9, 37, '23사이클이에요. 거의 안 썼습니다!', SYSTIMESTAMP - INTERVAL '2' DAY + INTERVAL '5' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r9, 38, '완전 새 거네요. 강남역 직거래 하고 싶어요!', SYSTIMESTAMP - INTERVAL '2' DAY + INTERVAL '10' MINUTE, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r9, 37, '좋아요! 내일 저녁 7시 강남역 2번 출구 어떠세요?', SYSTIMESTAMP - INTERVAL '2' DAY + INTERVAL '14' MINUTE, 'Y', 38);

  -- Room 10 (레고 포르쉐)
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r10, 38, '레고 미개봉 맞죠? 박스 상태는 어떤가요?', SYSTIMESTAMP - INTERVAL '1' DAY, 'Y', 37);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r10, 37, '완전 미개봉 박스 실링 그대로입니다!', SYSTIMESTAMP - INTERVAL '1' DAY + INTERVAL '3' MINUTE, 'Y', 38);
  INSERT INTO CHAT_MESSAGE (MSG_ID, ROOM_ID, SENDER_NO, MESSAGE, SENT_AT, IS_READ, RECEIVER_NO) VALUES (CHAT_MESSAGE_SEQ.NEXTVAL, r10, 38, '구매할게요!', SYSTIMESTAMP - INTERVAL '1' DAY + INTERVAL '7' MINUTE, 'Y', 37);


  /* ============================================================
     5. TRADE (거래 이력)
     ============================================================ */
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p1,  37, 38, SYSDATE - 9);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p2,  37, 38, SYSDATE - 8);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p3,  37, 38, SYSDATE - 7);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p4,  37, 38, SYSDATE - 6);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p5,  37, 38, SYSDATE - 5);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p6,  37, 38, SYSDATE - 4);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p7,  37, 38, SYSDATE - 3);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p8,  37, 38, SYSDATE - 2);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p9,  37, 38, SYSDATE - 1);
  INSERT INTO TRADE (PRODUCT_ID, SELLER_NO, BUYER_NO, TRADE_DATE) VALUES (p10, 37, 38, SYSDATE);


  /* ============================================================
     6. REVIEW (구매자 38 → 판매자 37, 별점 다양하게)
     ============================================================ */
  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p1, 38, 37, 5, '설명 그대로 완벽한 상태였어요. 빠른 거래 감사합니다!', SYSTIMESTAMP - INTERVAL '9' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p2, 38, 37, 5, '배터리도 정말 좋고 친절하게 거래해주셨어요. 강추!', SYSTIMESTAMP - INTERVAL '8' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p3, 38, 37, 4, '상품 상태 좋고 거래도 매끄럽게 잘 됐습니다.', SYSTIMESTAMP - INTERVAL '7' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p4, 38, 37, 5, '포장 꼼꼼하게 해주셔서 안전하게 받았어요. 감사해요!', SYSTIMESTAMP - INTERVAL '6' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p5, 38, 37, 4, '신발 상태 사진과 동일했어요. 믿을 수 있는 판매자!', SYSTIMESTAMP - INTERVAL '5' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p6, 38, 37, 3, '상품 상태는 괜찮은데 연락이 조금 느렸어요.', SYSTIMESTAMP - INTERVAL '4' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p7, 38, 37, 5, '다이슨 에어랩 구성품 완벽! 설명도 정확하고 친절하셨어요.', SYSTIMESTAMP - INTERVAL '3' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p8, 38, 37, 5, '텀블러 진짜 깨끗하게 왔어요. 또 거래하고 싶어요!', SYSTIMESTAMP - INTERVAL '2' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p9, 38, 37, 5, '맥북 완전 새 거나 다름없었어요. 최고의 판매자입니다!', SYSTIMESTAMP - INTERVAL '1' DAY);

  INSERT INTO REVIEW (REVIEW_ID, PRODUCT_ID, REVIEWER_NO, REVIEWEE_NO, RATING, CONTENT, REG_DATE)
  VALUES (REVIEW_SEQ.NEXTVAL, p10, 38, 37, 4, '레고 미개봉 확인했어요. 빠른 배송 감사합니다.', SYSTIMESTAMP);


  /* ============================================================
     7. MY_USER_PAGE 매너온도 갱신 (평균 4.5 → 63.0)
     ============================================================ */
  UPDATE MY_USER_PAGE
     SET TEMPERATURE = (
         SELECT ROUND(NVL(AVG(RATING) / 5.0 * 70, 36.5), 1)
         FROM REVIEW WHERE REVIEWEE_NO = 37
     )
   WHERE USER_NO = 37;


  COMMIT;
  DBMS_OUTPUT.PUT_LINE('✅ 테스트 데이터 삽입 완료');
  DBMS_OUTPUT.PUT_LINE('   상품 10건 / 파일 10건 / 채팅방 10개 / 메시지 37건 / 거래 10건 / 리뷰 10건');

END;
/
